export const UI_LANGUAGE_OPTIONS = [
  { code: 'en', nativeName: 'English', englishName: 'English' },
  { code: 'ru', nativeName: 'Русский', englishName: 'Russian' },
  { code: 'zh', nativeName: '中文', englishName: 'Chinese' },
  { code: 'es', nativeName: 'Español', englishName: 'Spanish' },
  { code: 'fr', nativeName: 'Français', englishName: 'French' },
  { code: 'de', nativeName: 'Deutsch', englishName: 'German' },
  { code: 'pt', nativeName: 'Português', englishName: 'Portuguese' },
  { code: 'it', nativeName: 'Italiano', englishName: 'Italian' },
  { code: 'ja', nativeName: '日本語', englishName: 'Japanese' },
  { code: 'ko', nativeName: '한국어', englishName: 'Korean' },
  { code: 'ar', nativeName: 'العربية', englishName: 'Arabic' },
  { code: 'tr', nativeName: 'Türkçe', englishName: 'Turkish' },
  { code: 'pl', nativeName: 'Polski', englishName: 'Polish' },
  { code: 'uk', nativeName: 'Українська', englishName: 'Ukrainian' },
  { code: 'nl', nativeName: 'Nederlands', englishName: 'Dutch' },
  { code: 'vi', nativeName: 'Tiếng Việt', englishName: 'Vietnamese' },
] as const;

export type UILanguage = typeof UI_LANGUAGE_OPTIONS[number]['code'];

type TranslationMap = Record<UILanguage, string>;

const all = (values: Partial<TranslationMap> & { en: string }): TranslationMap => ({
  en: values.en,
  ru: values.ru ?? values.en,
  zh: values.zh ?? values.en,
  es: values.es ?? values.en,
  fr: values.fr ?? values.en,
  de: values.de ?? values.en,
  pt: values.pt ?? values.en,
  it: values.it ?? values.en,
  ja: values.ja ?? values.en,
  ko: values.ko ?? values.en,
  ar: values.ar ?? values.en,
  tr: values.tr ?? values.en,
  pl: values.pl ?? values.en,
  uk: values.uk ?? values.en,
  nl: values.nl ?? values.en,
  vi: values.vi ?? values.en,
});

const translations = {
  // Header
  'header.title': all({ en: 'Translation Editor', ru: 'Редактор переводов', zh: '翻译编辑器', es: 'Editor de traducciones', fr: 'Éditeur de traductions', de: 'Übersetzungseditor', pt: 'Editor de traduções', it: 'Editor traduzioni', ja: '翻訳エディター', ko: '번역 편집기', ar: 'محرر الترجمات', tr: 'Çeviri düzenleyici', pl: 'Edytor tłumaczeń', uk: 'Редактор перекладів', nl: 'Vertaaleditor', vi: 'Trình chỉnh sửa bản dịch' }),
  'header.subtitle': all({ en: 'Translation file editor', ru: 'Редактор файлов переводов', zh: '翻译文件编辑器', es: 'Editor de archivos de traducción', fr: 'Éditeur de fichiers de traduction', de: 'Editor für Übersetzungsdateien', pt: 'Editor de arquivos de tradução', it: 'Editor file di traduzione', ja: '翻訳ファイルエディター', ko: '번역 파일 편집기', ar: 'محرر ملفات الترجمة', tr: 'Çeviri dosyası düzenleyici', pl: 'Edytor plików tłumaczeń', uk: 'Редактор файлів перекладу', nl: 'Editor voor vertaalbestanden', vi: 'Trình chỉnh sửa tệp dịch' }),
  'header.tab.editor': all({ en: 'Editor', ru: 'Редактор', zh: '编辑器', es: 'Editor', fr: 'Éditeur', de: 'Editor', pt: 'Editor', it: 'Editor', ja: 'エディター', ko: '편집기', ar: 'المحرر', tr: 'Editör', pl: 'Edytor', uk: 'Редактор', nl: 'Editor', vi: 'Trình sửa' }),
  'header.tab.requests': all({ en: 'Requests', ru: 'Запросы', zh: '请求', es: 'Solicitudes', fr: 'Demandes', de: 'Anfragen', pt: 'Solicitações', it: 'Richieste', ja: 'リクエスト', ko: '요청', ar: 'الطلبات', tr: 'İstekler', pl: 'Zgłoszenia', uk: 'Запити', nl: 'Verzoeken', vi: 'Yêu cầu' }),
  'header.tab.settings': all({ en: 'Settings', ru: 'Настройки', zh: '设置', es: 'Ajustes', fr: 'Paramètres', de: 'Einstellungen', pt: 'Configurações', it: 'Impostazioni', ja: '設定', ko: '설정', ar: 'الإعدادات', tr: 'Ayarlar', pl: 'Ustawienia', uk: 'Налаштування', nl: 'Instellingen', vi: 'Cài đặt' }),
  'header.admin': all({ en: 'Admin', ru: 'Админ', zh: '管理员', es: 'Admin', fr: 'Admin', de: 'Admin', pt: 'Admin', it: 'Admin', ja: '管理者', ko: '관리자', ar: 'مدير', tr: 'Yönetici', pl: 'Admin', uk: 'Адмін', nl: 'Beheerder', vi: 'Quản trị' }),
  'header.login': all({ en: 'Log in', ru: 'Войти', zh: '登录', es: 'Iniciar sesión', fr: 'Connexion', de: 'Anmelden', pt: 'Entrar', it: 'Accedi', ja: 'ログイン', ko: '로그인', ar: 'تسجيل الدخول', tr: 'Giriş yap', pl: 'Zaloguj', uk: 'Увійти', nl: 'Inloggen', vi: 'Đăng nhập' }),
  'header.logout': all({ en: 'Log out', ru: 'Выйти', zh: '退出', es: 'Cerrar sesión', fr: 'Déconnexion', de: 'Abmelden', pt: 'Sair', it: 'Esci', ja: 'ログアウト', ko: '로그아웃', ar: 'تسجيل الخروج', tr: 'Çıkış yap', pl: 'Wyloguj', uk: 'Вийти', nl: 'Uitloggen', vi: 'Đăng xuất' }),
  'header.loginTitle': all({ en: 'Administrator login', ru: 'Вход администратора', zh: '管理员登录', es: 'Acceso de administrador', fr: 'Connexion administrateur', de: 'Administratoranmeldung', pt: 'Login do administrador', it: 'Accesso amministratore', ja: '管理者ログイン', ko: '관리자 로그인', ar: 'تسجيل دخول المدير', tr: 'Yönetici girişi', pl: 'Logowanie administratora', uk: 'Вхід адміністратора', nl: 'Beheerderslogin', vi: 'Đăng nhập quản trị' }),
  'header.loginError': all({ en: 'Invalid username or password', ru: 'Неверный логин или пароль', zh: '用户名或密码无效', es: 'Usuario o contraseña no válidos', fr: 'Nom d’utilisateur ou mot de passe invalide', de: 'Ungültiger Benutzername oder Passwort', pt: 'Nome de usuário ou senha inválidos', it: 'Nome utente o password non validi', ja: 'ユーザー名またはパスワードが無効です', ko: '사용자 이름 또는 비밀번호가 올바르지 않습니다', ar: 'اسم المستخدم أو كلمة المرور غير صحيحة', tr: 'Kullanıcı adı veya parola geçersiz', pl: 'Nieprawidłowa nazwa użytkownika lub hasło', uk: 'Невірний логін або пароль', nl: 'Ongeldige gebruikersnaam of wachtwoord', vi: 'Tên người dùng hoặc mật khẩu không hợp lệ' }),
  'header.username': all({ en: 'Username', ru: 'Логин', zh: '用户名', es: 'Usuario', fr: 'Nom d’utilisateur', de: 'Benutzername', pt: 'Usuário', it: 'Nome utente', ja: 'ユーザー名', ko: '사용자 이름', ar: 'اسم المستخدم', tr: 'Kullanıcı adı', pl: 'Nazwa użytkownika', uk: 'Логін', nl: 'Gebruikersnaam', vi: 'Tên người dùng' }),
  'header.password': all({ en: 'Password', ru: 'Пароль', zh: '密码', es: 'Contraseña', fr: 'Mot de passe', de: 'Passwort', pt: 'Senha', it: 'Password', ja: 'パスワード', ko: '비밀번호', ar: 'كلمة المرور', tr: 'Parola', pl: 'Hasło', uk: 'Пароль', nl: 'Wachtwoord', vi: 'Mật khẩu' }),
  'header.cancel': all({ en: 'Cancel', ru: 'Отмена', zh: '取消', es: 'Cancelar', fr: 'Annuler', de: 'Abbrechen', pt: 'Cancelar', it: 'Annulla', ja: 'キャンセル', ko: '취소', ar: 'إلغاء', tr: 'İptal', pl: 'Anuluj', uk: 'Скасувати', nl: 'Annuleren', vi: 'Hủy' }),
  'header.uiLanguage': all({ en: 'Interface language', ru: 'Язык интерфейса', zh: '界面语言', es: 'Idioma de la interfaz', fr: 'Langue de l’interface', de: 'Sprache der Oberfläche', pt: 'Idioma da interface', it: 'Lingua interfaccia', ja: '表示言語', ko: '인터페이스 언어', ar: 'لغة الواجهة', tr: 'Arayüz dili', pl: 'Język interfejsu', uk: 'Мова інтерфейсу', nl: 'Interfacetaal', vi: 'Ngôn ngữ giao diện' }),
  'header.theme': all({ en: 'Theme tone', ru: 'Тон оформления', zh: '主题色调', es: 'Tono del tema', fr: 'Ton du thème', de: 'Design-Ton', pt: 'Tom do tema', it: 'Tono tema', ja: 'テーマトーン', ko: '테마 톤', ar: 'نمط السمة', tr: 'Tema tonu', pl: 'Ton motywu', uk: 'Тон оформлення', nl: 'Themakleur', vi: 'Tông giao diện' }),

  // Language selector
  'sidebar.files': all({ en: 'Localization files', ru: 'Файлы локализации', zh: '本地化文件', es: 'Archivos de localización', fr: 'Fichiers de localisation', de: 'Lokalisierungsdateien', pt: 'Arquivos de localização', it: 'File di localizzazione', ja: 'ローカライズファイル', ko: '현지화 파일', ar: 'ملفات التوطين', tr: 'Yerelleştirme dosyaları', pl: 'Pliki lokalizacji', uk: 'Файли локалізації', nl: 'Lokalisatiebestanden', vi: 'Tệp bản địa hóa' }),
  'sidebar.lines': all({ en: 'lines', ru: 'строк', zh: '行', es: 'líneas', fr: 'lignes', de: 'Zeilen', pt: 'linhas', it: 'righe', ja: '行', ko: '줄', ar: 'أسطر', tr: 'satır', pl: 'wierszy', uk: 'рядків', nl: 'regels', vi: 'dòng' }),
  'sidebar.loading': all({ en: 'Loading', ru: 'Загрузка', zh: '加载中', es: 'Cargando', fr: 'Chargement', de: 'Lädt', pt: 'Carregando', it: 'Caricamento', ja: '読み込み中', ko: '로딩 중', ar: 'جارٍ التحميل', tr: 'Yükleniyor', pl: 'Ładowanie', uk: 'Завантаження', nl: 'Laden', vi: 'Đang tải' }),
  'sidebar.loadingFile': all({ en: 'Loading file...', ru: 'Файл загружается...', zh: '正在加载文件...', es: 'Cargando archivo...', fr: 'Chargement du fichier...', de: 'Datei wird geladen...', pt: 'Carregando arquivo...', it: 'File in caricamento...', ja: 'ファイルを読み込み中...', ko: '파일 로딩 중...', ar: 'جارٍ تحميل الملف...', tr: 'Dosya yükleniyor...', pl: 'Ładowanie pliku...', uk: 'Файл завантажується...', nl: 'Bestand laden...', vi: 'Đang tải tệp...' }),

  // Top contributors
  'top.title': all({ en: 'Top contributors', ru: 'Топ контрибьюторов', zh: '贡献者排行', es: 'Colaboradores principales', fr: 'Meilleurs contributeurs', de: 'Top-Mitwirkende', pt: 'Principais colaboradores', it: 'Migliori contributori', ja: '上位貢献者', ko: '상위 기여자', ar: 'أفضل المساهمين', tr: 'En iyi katkıda bulunanlar', pl: 'Najlepsi współtwórcy', uk: 'Топ контриб’юторів', nl: 'Topbijdragers', vi: 'Người đóng góp hàng đầu' }),
  'top.subtitle': all({ en: 'By accepted translated text', ru: 'По количеству переведенного текста', zh: '按已接受译文量', es: 'Por texto traducido aceptado', fr: 'Par texte traduit accepté', de: 'Nach akzeptiertem übersetztem Text', pt: 'Por texto traduzido aceito', it: 'Per testo tradotto accettato', ja: '承認済み翻訳量順', ko: '승인된 번역 텍스트 기준', ar: 'حسب النص المترجم المقبول', tr: 'Kabul edilen çeviri metnine göre', pl: 'Według zaakceptowanego tekstu', uk: 'За кількістю прийнятого перекладу', nl: 'Op geaccepteerde vertaalde tekst', vi: 'Theo văn bản dịch đã duyệt' }),
  'top.unit': all({ en: 'chars', ru: 'симв.', zh: '字符', es: 'car.', fr: 'car.', de: 'Zeichen', pt: 'car.', it: 'car.', ja: '文字', ko: '자', ar: 'حرف', tr: 'kar.', pl: 'znaków', uk: 'симв.', nl: 'tekens', vi: 'ký tự' }),

  // Editor
  'editor.selectFile': all({ en: 'Select a file', ru: 'Выберите файл', zh: '选择文件', es: 'Selecciona un archivo', fr: 'Sélectionnez un fichier', de: 'Datei auswählen', pt: 'Selecione um arquivo', it: 'Seleziona un file', ja: 'ファイルを選択', ko: '파일 선택', ar: 'اختر ملفًا', tr: 'Dosya seç', pl: 'Wybierz plik', uk: 'Виберіть файл', nl: 'Selecteer een bestand', vi: 'Chọn tệp' }),
  'editor.selectFileDesc': all({ en: 'Select a localization file from the list on the left to start editing translations', ru: 'Выберите файл локализации из списка слева, чтобы начать редактирование переводов', zh: '从左侧列表选择本地化文件以开始编辑翻译', es: 'Selecciona un archivo de localización de la lista izquierda para empezar a editar', fr: 'Sélectionnez un fichier de localisation dans la liste de gauche pour commencer', de: 'Wählen Sie links eine Lokalisierungsdatei aus, um Übersetzungen zu bearbeiten', pt: 'Selecione um arquivo de localização à esquerda para começar a editar', it: 'Seleziona un file di localizzazione a sinistra per iniziare', ja: '左の一覧からローカライズファイルを選択して編集を開始します', ko: '왼쪽 목록에서 현지화 파일을 선택해 번역을 편집하세요', ar: 'اختر ملف توطين من القائمة اليسرى لبدء التحرير', tr: 'Çevirileri düzenlemek için soldan bir yerelleştirme dosyası seçin', pl: 'Wybierz plik lokalizacji z listy po lewej, aby rozpocząć edycję', uk: 'Виберіть файл локалізації зі списку ліворуч, щоб почати редагування', nl: 'Selecteer links een lokalisatiebestand om vertalingen te bewerken', vi: 'Chọn tệp bản địa hóa bên trái để bắt đầu chỉnh sửa' }),
  'editor.total': all({ en: 'total', ru: 'всего', zh: '总计', es: 'total', fr: 'total', de: 'gesamt', pt: 'total', it: 'totale', ja: '合計', ko: '전체', ar: 'الإجمالي', tr: 'toplam', pl: 'łącznie', uk: 'всього', nl: 'totaal', vi: 'tổng' }),
  'editor.translated': all({ en: 'translated', ru: 'переведено', zh: '已翻译', es: 'traducidas', fr: 'traduites', de: 'übersetzt', pt: 'traduzidas', it: 'tradotte', ja: '翻訳済み', ko: '번역됨', ar: 'مترجم', tr: 'çevrildi', pl: 'przetłumaczono', uk: 'перекладено', nl: 'vertaald', vi: 'đã dịch' }),
  'editor.untranslated': all({ en: 'untranslated', ru: 'не переведено', zh: '未翻译', es: 'sin traducir', fr: 'non traduites', de: 'nicht übersetzt', pt: 'não traduzidas', it: 'non tradotte', ja: '未翻訳', ko: '미번역', ar: 'غير مترجم', tr: 'çevrilmedi', pl: 'nieprzetłumaczone', uk: 'не перекладено', nl: 'onvertaald', vi: 'chưa dịch' }),
  'editor.searchPlaceholder': all({ en: 'Search by original or translation...', ru: 'Поиск по оригиналу или переводу...', zh: '按原文或译文搜索...', es: 'Buscar por original o traducción...', fr: 'Rechercher par original ou traduction...', de: 'Nach Original oder Übersetzung suchen...', pt: 'Buscar por original ou tradução...', it: 'Cerca originale o traduzione...', ja: '原文または翻訳で検索...', ko: '원문 또는 번역으로 검색...', ar: 'ابحث بالأصل أو الترجمة...', tr: 'Orijinal veya çeviriye göre ara...', pl: 'Szukaj po oryginale lub tłumaczeniu...', uk: 'Пошук за оригіналом або перекладом...', nl: 'Zoek op origineel of vertaling...', vi: 'Tìm theo bản gốc hoặc bản dịch...' }),
  'editor.filterAll': all({ en: 'All', ru: 'Все', zh: '全部', es: 'Todas', fr: 'Tout', de: 'Alle', pt: 'Tudo', it: 'Tutte', ja: 'すべて', ko: '전체', ar: 'الكل', tr: 'Tümü', pl: 'Wszystkie', uk: 'Усі', nl: 'Alles', vi: 'Tất cả' }),
  'editor.filterTranslated': all({ en: 'Translated', ru: 'Переведено', zh: '已翻译', es: 'Traducidas', fr: 'Traduites', de: 'Übersetzt', pt: 'Traduzidas', it: 'Tradotte', ja: '翻訳済み', ko: '번역됨', ar: 'مترجم', tr: 'Çevrildi', pl: 'Przetłumaczone', uk: 'Перекладено', nl: 'Vertaald', vi: 'Đã dịch' }),
  'editor.filterUntranslated': all({ en: 'Untranslated', ru: 'Не переведено', zh: '未翻译', es: 'Sin traducir', fr: 'Non traduites', de: 'Nicht übersetzt', pt: 'Não traduzidas', it: 'Non tradotte', ja: '未翻訳', ko: '미번역', ar: 'غير مترجم', tr: 'Çevrilmedi', pl: 'Nieprzetłumaczone', uk: 'Не перекладено', nl: 'Onvertaald', vi: 'Chưa dịch' }),
  'editor.filterChanged': all({ en: 'Changed by you', ru: 'Вами измененные', zh: '你修改的', es: 'Modificadas por ti', fr: 'Modifiées par vous', de: 'Von Ihnen geändert', pt: 'Alteradas por você', it: 'Modificate da te', ja: '自分の変更', ko: '내가 변경함', ar: 'عدّلتها أنت', tr: 'Sizin değiştirdikleriniz', pl: 'Zmienione przez Ciebie', uk: 'Змінені вами', nl: 'Door jou gewijzigd', vi: 'Bạn đã thay đổi' }),
  'editor.enterTranslation': all({ en: 'Enter translation...', ru: 'Введите перевод...', zh: '输入翻译...', es: 'Introduce la traducción...', fr: 'Saisir la traduction...', de: 'Übersetzung eingeben...', pt: 'Digite a tradução...', it: 'Inserisci traduzione...', ja: '翻訳を入力...', ko: '번역 입력...', ar: 'أدخل الترجمة...', tr: 'Çeviri gir...', pl: 'Wpisz tłumaczenie...', uk: 'Введіть переклад...', nl: 'Voer vertaling in...', vi: 'Nhập bản dịch...' }),
  'editor.matchesOriginal': all({ en: '⚠ Translation matches original', ru: '⚠ Перевод совпадает с оригиналом', zh: '⚠ 译文与原文相同', es: '⚠ La traducción coincide con el original', fr: '⚠ La traduction correspond à l’original', de: '⚠ Übersetzung entspricht dem Original', pt: '⚠ A tradução é igual ao original', it: '⚠ La traduzione coincide con l’originale', ja: '⚠ 翻訳が原文と同じです', ko: '⚠ 번역이 원문과 같습니다', ar: '⚠ الترجمة تطابق الأصل', tr: '⚠ Çeviri orijinalle aynı', pl: '⚠ Tłumaczenie jest takie jak oryginał', uk: '⚠ Переклад збігається з оригіналом', nl: '⚠ Vertaling komt overeen met origineel', vi: '⚠ Bản dịch trùng với bản gốc' }),
  'editor.entriesOf': all({ en: 'of', ru: 'из', zh: '/', es: 'de', fr: 'sur', de: 'von', pt: 'de', it: 'di', ja: '/', ko: '/', ar: 'من', tr: '/', pl: 'z', uk: 'з', nl: 'van', vi: 'trên' }),
  'editor.entries': all({ en: 'entries', ru: 'записей', zh: '条', es: 'entradas', fr: 'entrées', de: 'Einträge', pt: 'entradas', it: 'voci', ja: '件', ko: '개 항목', ar: 'إدخالات', tr: 'kayıt', pl: 'wpisów', uk: 'записів', nl: 'items', vi: 'mục' }),
  'editor.changed': all({ en: 'changed', ru: 'изменено', zh: '已更改', es: 'cambiadas', fr: 'modifiées', de: 'geändert', pt: 'alteradas', it: 'modificate', ja: '変更済み', ko: '변경됨', ar: 'مغيّر', tr: 'değişti', pl: 'zmienione', uk: 'змінено', nl: 'gewijzigd', vi: 'đã đổi' }),
  'editor.reset': all({ en: 'Reset', ru: 'Сбросить', zh: '重置', es: 'Restablecer', fr: 'Réinitialiser', de: 'Zurücksetzen', pt: 'Redefinir', it: 'Ripristina', ja: 'リセット', ko: '초기화', ar: 'إعادة تعيين', tr: 'Sıfırla', pl: 'Resetuj', uk: 'Скинути', nl: 'Resetten', vi: 'Đặt lại' }),
  'editor.applyChanges': all({ en: 'Apply changes', ru: 'Применить изменения', zh: '应用更改', es: 'Aplicar cambios', fr: 'Appliquer les modifications', de: 'Änderungen anwenden', pt: 'Aplicar alterações', it: 'Applica modifiche', ja: '変更を適用', ko: '변경 적용', ar: 'تطبيق التغييرات', tr: 'Değişiklikleri uygula', pl: 'Zastosuj zmiany', uk: 'Застосувати зміни', nl: 'Wijzigingen toepassen', vi: 'Áp dụng thay đổi' }),
  'editor.submitRequest': all({ en: 'Submit request', ru: 'Отправить запрос', zh: '提交请求', es: 'Enviar solicitud', fr: 'Envoyer la demande', de: 'Anfrage senden', pt: 'Enviar solicitação', it: 'Invia richiesta', ja: 'リクエスト送信', ko: '요청 제출', ar: 'إرسال الطلب', tr: 'İstek gönder', pl: 'Wyślij zgłoszenie', uk: 'Надіслати запит', nl: 'Verzoek indienen', vi: 'Gửi yêu cầu' }),
  'editor.sync': all({ en: 'Synchronize', ru: 'Синхронизировать', zh: '同步', es: 'Sincronizar', fr: 'Synchroniser', de: 'Synchronisieren', pt: 'Sincronizar', it: 'Sincronizza', ja: '同期', ko: '동기화', ar: 'مزامنة', tr: 'Eşitle', pl: 'Synchronizuj', uk: 'Синхронізувати', nl: 'Synchroniseren', vi: 'Đồng bộ' }),
  'editor.syncing': all({ en: 'Synchronizing...', ru: 'Синхронизация...', zh: '正在同步...', es: 'Sincronizando...', fr: 'Synchronisation...', de: 'Synchronisiere...', pt: 'Sincronizando...', it: 'Sincronizzazione...', ja: '同期中...', ko: '동기화 중...', ar: 'جارٍ المزامنة...', tr: 'Eşitleniyor...', pl: 'Synchronizowanie...', uk: 'Синхронізація...', nl: 'Synchroniseren...', vi: 'Đang đồng bộ...' }),
  'editor.syncSuccess': all({ en: 'Strings synchronized from file', ru: 'Строки синхронизированы из файла', zh: '字符串已从文件同步', es: 'Cadenas sincronizadas desde el archivo', fr: 'Chaînes synchronisées depuis le fichier', de: 'Zeilen aus Datei synchronisiert', pt: 'Strings sincronizadas do arquivo', it: 'Stringhe sincronizzate dal file', ja: 'ファイルから文字列を同期しました', ko: '파일에서 문자열을 동기화했습니다', ar: 'تمت مزامنة النصوص من الملف', tr: 'Dizeler dosyadan eşitlendi', pl: 'Ciągi zsynchronizowane z pliku', uk: 'Рядки синхронізовано з файлу', nl: 'Strings gesynchroniseerd vanuit bestand', vi: 'Đã đồng bộ chuỗi từ tệp' }),
  'editor.syncError': all({ en: 'Synchronization failed', ru: 'Ошибка синхронизации', zh: '同步失败', es: 'Error de sincronización', fr: 'Échec de la synchronisation', de: 'Synchronisierung fehlgeschlagen', pt: 'Falha na sincronização', it: 'Sincronizzazione non riuscita', ja: '同期に失敗しました', ko: '동기화 실패', ar: 'فشلت المزامنة', tr: 'Eşitleme başarısız', pl: 'Synchronizacja nie powiodła się', uk: 'Помилка синхронізації', nl: 'Synchronisatie mislukt', vi: 'Đồng bộ thất bại' }),
  'editor.changesApplied': all({ en: 'Changes applied successfully!', ru: 'Изменения успешно применены!', zh: '更改已成功应用！', es: '¡Cambios aplicados correctamente!', fr: 'Modifications appliquées avec succès !', de: 'Änderungen erfolgreich angewendet!', pt: 'Alterações aplicadas com sucesso!', it: 'Modifiche applicate con successo!', ja: '変更を適用しました！', ko: '변경 사항이 적용되었습니다!', ar: 'تم تطبيق التغييرات بنجاح!', tr: 'Değişiklikler başarıyla uygulandı!', pl: 'Zmiany zastosowane pomyślnie!', uk: 'Зміни успішно застосовано!', nl: 'Wijzigingen succesvol toegepast!', vi: 'Đã áp dụng thay đổi!' }),
  'editor.requestSent': all({ en: 'Request submitted successfully!', ru: 'Запрос успешно отправлен!', zh: '请求已成功提交！', es: '¡Solicitud enviada correctamente!', fr: 'Demande envoyée avec succès !', de: 'Anfrage erfolgreich gesendet!', pt: 'Solicitação enviada com sucesso!', it: 'Richiesta inviata con successo!', ja: 'リクエストを送信しました！', ko: '요청이 제출되었습니다!', ar: 'تم إرسال الطلب بنجاح!', tr: 'İstek başarıyla gönderildi!', pl: 'Zgłoszenie wysłane pomyślnie!', uk: 'Запит успішно надіслано!', nl: 'Verzoek succesvol ingediend!', vi: 'Đã gửi yêu cầu!' }),
  'editor.nothingFound': all({ en: 'Nothing found', ru: 'Ничего не найдено', zh: '未找到', es: 'No se encontró nada', fr: 'Rien trouvé', de: 'Nichts gefunden', pt: 'Nada encontrado', it: 'Nessun risultato', ja: '見つかりません', ko: '찾을 수 없음', ar: 'لم يتم العثور على شيء', tr: 'Bir şey bulunamadı', pl: 'Nic nie znaleziono', uk: 'Нічого не знайдено', nl: 'Niets gevonden', vi: 'Không tìm thấy' }),
  'editor.original': all({ en: 'Original', ru: 'Оригинал', zh: '原文', es: 'Original', fr: 'Original', de: 'Original', pt: 'Original', it: 'Originale', ja: '原文', ko: '원문', ar: 'الأصل', tr: 'Orijinal', pl: 'Oryginał', uk: 'Оригінал', nl: 'Origineel', vi: 'Bản gốc' }),
  'editor.translation': all({ en: 'Translation', ru: 'Перевод', zh: '译文', es: 'Traducción', fr: 'Traduction', de: 'Übersetzung', pt: 'Tradução', it: 'Traduzione', ja: '翻訳', ko: '번역', ar: 'الترجمة', tr: 'Çeviri', pl: 'Tłumaczenie', uk: 'Переклад', nl: 'Vertaling', vi: 'Bản dịch' }),
  'editor.copyOriginal': all({ en: 'Copy original', ru: 'Вставить оригинал', zh: '复制原文', es: 'Copiar original', fr: 'Copier l’original', de: 'Original kopieren', pt: 'Copiar original', it: 'Copia originale', ja: '原文をコピー', ko: '원문 복사', ar: 'نسخ الأصل', tr: 'Orijinali kopyala', pl: 'Kopiuj oryginał', uk: 'Копіювати оригінал', nl: 'Origineel kopiëren', vi: 'Sao chép bản gốc' }),
  'editor.clear': all({ en: 'Clear', ru: 'Очистить', zh: '清除', es: 'Limpiar', fr: 'Effacer', de: 'Leeren', pt: 'Limpar', it: 'Cancella', ja: 'クリア', ko: '지우기', ar: 'مسح', tr: 'Temizle', pl: 'Wyczyść', uk: 'Очистити', nl: 'Wissen', vi: 'Xóa' }),
  'editor.revert': all({ en: 'Revert', ru: 'Вернуть', zh: '还原', es: 'Revertir', fr: 'Rétablir', de: 'Zurücksetzen', pt: 'Reverter', it: 'Annulla modifiche', ja: '元に戻す', ko: '되돌리기', ar: 'تراجع', tr: 'Geri al', pl: 'Przywróć', uk: 'Повернути', nl: 'Terugzetten', vi: 'Hoàn nguyên' }),
  'editor.nextField': all({ en: 'Next', ru: 'Далее', zh: '下一步', es: 'Siguiente', fr: 'Suivant', de: 'Weiter', pt: 'Próximo', it: 'Avanti', ja: '次へ', ko: '다음', ar: 'التالي', tr: 'Sonraki', pl: 'Dalej', uk: 'Далі', nl: 'Volgende', vi: 'Tiếp' }),
  'editor.nextHint': all({ en: 'Ctrl+Enter moves to the next field', ru: 'Ctrl+Enter переходит к следующему полю', zh: 'Ctrl+Enter 移至下一个字段', es: 'Ctrl+Enter pasa al siguiente campo', fr: 'Ctrl+Entrée passe au champ suivant', de: 'Strg+Enter wechselt zum nächsten Feld', pt: 'Ctrl+Enter vai para o próximo campo', it: 'Ctrl+Invio passa al campo successivo', ja: 'Ctrl+Enter で次のフィールドへ移動', ko: 'Ctrl+Enter로 다음 필드로 이동', ar: 'Ctrl+Enter ينتقل إلى الحقل التالي', tr: 'Ctrl+Enter sonraki alana geçer', pl: 'Ctrl+Enter przechodzi do następnego pola', uk: 'Ctrl+Enter переходить до наступного поля', nl: 'Ctrl+Enter gaat naar het volgende veld', vi: 'Ctrl+Enter chuyển sang trường tiếp theo' }),
  'editor.characters': all({ en: 'characters', ru: 'симв.', zh: '字符', es: 'caracteres', fr: 'caractères', de: 'Zeichen', pt: 'caracteres', it: 'caratteri', ja: '文字', ko: '자', ar: 'أحرف', tr: 'karakter', pl: 'znaków', uk: 'символів', nl: 'tekens', vi: 'ký tự' }),

  // Submit modal
  'modal.titleAdmin': all({ en: 'Apply changes', ru: 'Применить изменения', zh: '应用更改', es: 'Aplicar cambios', fr: 'Appliquer les modifications', de: 'Änderungen anwenden', pt: 'Aplicar alterações', it: 'Applica modifiche', ja: '変更を適用', ko: '변경 적용', ar: 'تطبيق التغييرات', tr: 'Değişiklikleri uygula', pl: 'Zastosuj zmiany', uk: 'Застосувати зміни', nl: 'Wijzigingen toepassen', vi: 'Áp dụng thay đổi' }),
  'modal.titleGuest': all({ en: 'Submit a change request', ru: 'Отправить запрос на изменение', zh: '提交更改请求', es: 'Enviar solicitud de cambio', fr: 'Envoyer une demande de modification', de: 'Änderungsanfrage senden', pt: 'Enviar solicitação de alteração', it: 'Invia richiesta di modifica', ja: '変更リクエストを送信', ko: '변경 요청 제출', ar: 'إرسال طلب تغيير', tr: 'Değişiklik isteği gönder', pl: 'Wyślij zgłoszenie zmiany', uk: 'Надіслати запит на зміну', nl: 'Wijzigingsverzoek indienen', vi: 'Gửi yêu cầu thay đổi' }),
  'modal.applyTitle': all({ en: 'Apply changes', ru: 'Применить изменения', zh: '应用更改', es: 'Aplicar cambios', fr: 'Appliquer les modifications', de: 'Änderungen anwenden', pt: 'Aplicar alterações', it: 'Applica modifiche', ja: '変更を適用', ko: '변경 적용', ar: 'تطبيق التغييرات', tr: 'Değişiklikleri uygula', pl: 'Zastosuj zmiany', uk: 'Застосувати зміни', nl: 'Wijzigingen toepassen', vi: 'Áp dụng thay đổi' }),
  'modal.submitTitle': all({ en: 'Submit a change request', ru: 'Отправить запрос на изменение', zh: '提交更改请求', es: 'Enviar solicitud de cambio', fr: 'Envoyer une demande de modification', de: 'Änderungsanfrage senden', pt: 'Enviar solicitação de alteração', it: 'Invia richiesta di modifica', ja: '変更リクエストを送信', ko: '변경 요청 제출', ar: 'إرسال طلب تغيير', tr: 'Değişiklik isteği gönder', pl: 'Wyślij zgłoszenie zmiany', uk: 'Надіслати запит на зміну', nl: 'Wijzigingsverzoek indienen', vi: 'Gửi yêu cầu thay đổi' }),
  'modal.changesFor': all({ en: 'changes for', ru: 'изменений для', zh: '项更改：', es: 'cambios para', fr: 'modifications pour', de: 'Änderungen für', pt: 'alterações para', it: 'modifiche per', ja: '件の変更:', ko: '변경 대상', ar: 'تغييرات لـ', tr: 'için değişiklik', pl: 'zmian dla', uk: 'змін для', nl: 'wijzigingen voor', vi: 'thay đổi cho' }),
  'modal.changesReady': all({ en: 'changes ready', ru: 'изменений готово', zh: '项更改已准备', es: 'cambios listos', fr: 'modifications prêtes', de: 'Änderungen bereit', pt: 'alterações prontas', it: 'modifiche pronte', ja: '件の変更が準備完了', ko: '변경 준비됨', ar: 'تغييرات جاهزة', tr: 'değişiklik hazır', pl: 'zmian gotowych', uk: 'змін готово', nl: 'wijzigingen klaar', vi: 'thay đổi sẵn sàng' }),
  'modal.authorLabel': all({ en: 'Your name / nickname', ru: 'Ваше имя / никнейм', zh: '你的姓名 / 昵称', es: 'Tu nombre / apodo', fr: 'Votre nom / pseudo', de: 'Ihr Name / Spitzname', pt: 'Seu nome / apelido', it: 'Nome / nickname', ja: '名前 / ニックネーム', ko: '이름 / 닉네임', ar: 'اسمك / لقبك', tr: 'Adınız / takma adınız', pl: 'Twoje imię / pseudonim', uk: 'Ваше ім’я / нікнейм', nl: 'Je naam / bijnaam', vi: 'Tên / biệt danh của bạn' }),
  'modal.authorName': all({ en: 'Your name / nickname', ru: 'Ваше имя / никнейм', zh: '你的姓名 / 昵称', es: 'Tu nombre / apodo', fr: 'Votre nom / pseudo', de: 'Ihr Name / Spitzname', pt: 'Seu nome / apelido', it: 'Nome / nickname', ja: '名前 / ニックネーム', ko: '이름 / 닉네임', ar: 'اسمك / لقبك', tr: 'Adınız / takma adınız', pl: 'Twoje imię / pseudonim', uk: 'Ваше ім’я / нікнейм', nl: 'Je naam / bijnaam', vi: 'Tên / biệt danh của bạn' }),
  'modal.authorPlaceholder': all({ en: 'e.g. John or Translator42', ru: 'Например: Иван или Translator42', zh: '例如：John 或 Translator42', es: 'p. ej. Juan o Translator42', fr: 'ex. Jean ou Translator42', de: 'z. B. John oder Translator42', pt: 'ex.: João ou Translator42', it: 'es. Mario o Translator42', ja: '例: John または Translator42', ko: '예: John 또는 Translator42', ar: 'مثال: John أو Translator42', tr: 'örn. John veya Translator42', pl: 'np. Jan lub Translator42', uk: 'Наприклад: Іван або Translator42', nl: 'bijv. Jan of Translator42', vi: 'vd. John hoặc Translator42' }),
  'modal.nameLabel': all({ en: 'Request title', ru: 'Название запроса', zh: '请求标题', es: 'Título de la solicitud', fr: 'Titre de la demande', de: 'Anfragetitel', pt: 'Título da solicitação', it: 'Titolo richiesta', ja: 'リクエストタイトル', ko: '요청 제목', ar: 'عنوان الطلب', tr: 'İstek başlığı', pl: 'Tytuł zgłoszenia', uk: 'Назва запиту', nl: 'Titel van verzoek', vi: 'Tiêu đề yêu cầu' }),
  'modal.requestName': all({ en: 'Request title', ru: 'Название запроса', zh: '请求标题', es: 'Título de la solicitud', fr: 'Titre de la demande', de: 'Anfragetitel', pt: 'Título da solicitação', it: 'Titolo richiesta', ja: 'リクエストタイトル', ko: '요청 제목', ar: 'عنوان الطلب', tr: 'İstek başlığı', pl: 'Tytuł zgłoszenia', uk: 'Назва запиту', nl: 'Titel van verzoek', vi: 'Tiêu đề yêu cầu' }),
  'modal.namePlaceholder': all({ en: 'e.g. Fix typos in menu', ru: 'Например: Исправление опечаток в меню', zh: '例如：修复菜单错别字', es: 'p. ej. Corregir erratas del menú', fr: 'ex. Corriger des fautes dans le menu', de: 'z. B. Tippfehler im Menü beheben', pt: 'ex.: Corrigir erros no menu', it: 'es. Correzione refusi nel menu', ja: '例: メニューの誤字修正', ko: '예: 메뉴 오타 수정', ar: 'مثال: إصلاح أخطاء القائمة', tr: 'örn. Menü yazım hatalarını düzelt', pl: 'np. Popraw literówki w menu', uk: 'Наприклад: Виправлення помилок у меню', nl: 'bijv. typfouten in menu herstellen', vi: 'vd. Sửa lỗi chính tả trong menu' }),
  'modal.preview': all({ en: 'Preview changes:', ru: 'Предпросмотр изменений:', zh: '预览更改：', es: 'Vista previa de cambios:', fr: 'Aperçu des modifications :', de: 'Änderungen anzeigen:', pt: 'Prévia das alterações:', it: 'Anteprima modifiche:', ja: '変更プレビュー:', ko: '변경 미리보기:', ar: 'معاينة التغييرات:', tr: 'Değişiklik önizlemesi:', pl: 'Podgląd zmian:', uk: 'Попередній перегляд змін:', nl: 'Voorbeeld van wijzigingen:', vi: 'Xem trước thay đổi:' }),
  'modal.empty': all({ en: '(empty)', ru: '(пусто)', zh: '（空）', es: '(vacío)', fr: '(vide)', de: '(leer)', pt: '(vazio)', it: '(vuoto)', ja: '（空）', ko: '(비어 있음)', ar: '(فارغ)', tr: '(boş)', pl: '(puste)', uk: '(порожньо)', nl: '(leeg)', vi: '(trống)' }),
  'modal.cancel': all({ en: 'Cancel', ru: 'Отмена', zh: '取消', es: 'Cancelar', fr: 'Annuler', de: 'Abbrechen', pt: 'Cancelar', it: 'Annulla', ja: 'キャンセル', ko: '취소', ar: 'إلغاء', tr: 'İptal', pl: 'Anuluj', uk: 'Скасувати', nl: 'Annuleren', vi: 'Hủy' }),
  'modal.apply': all({ en: 'Apply', ru: 'Применить', zh: '应用', es: 'Aplicar', fr: 'Appliquer', de: 'Anwenden', pt: 'Aplicar', it: 'Applica', ja: '適用', ko: '적용', ar: 'تطبيق', tr: 'Uygula', pl: 'Zastosuj', uk: 'Застосувати', nl: 'Toepassen', vi: 'Áp dụng' }),
  'modal.submit': all({ en: 'Submit', ru: 'Отправить', zh: '提交', es: 'Enviar', fr: 'Envoyer', de: 'Senden', pt: 'Enviar', it: 'Invia', ja: '送信', ko: '제출', ar: 'إرسال', tr: 'Gönder', pl: 'Wyślij', uk: 'Надіслати', nl: 'Indienen', vi: 'Gửi' }),

  // Change requests
  'requests.title': all({ en: 'Change requests', ru: 'Запросы на изменение', zh: '更改请求', es: 'Solicitudes de cambio', fr: 'Demandes de modification', de: 'Änderungsanfragen', pt: 'Solicitações de alteração', it: 'Richieste di modifica', ja: '変更リクエスト', ko: '변경 요청', ar: 'طلبات التغيير', tr: 'Değişiklik istekleri', pl: 'Zgłoszenia zmian', uk: 'Запити на зміну', nl: 'Wijzigingsverzoeken', vi: 'Yêu cầu thay đổi' }),
  'requests.pending': all({ en: 'pending', ru: 'ожидающих', zh: '待处理', es: 'pendientes', fr: 'en attente', de: 'ausstehend', pt: 'pendentes', it: 'in attesa', ja: '保留中', ko: '대기 중', ar: 'قيد الانتظار', tr: 'bekliyor', pl: 'oczekujące', uk: 'очікують', nl: 'in behandeling', vi: 'đang chờ' }),
  'requests.all': all({ en: 'All', ru: 'Все', zh: '全部', es: 'Todas', fr: 'Tout', de: 'Alle', pt: 'Tudo', it: 'Tutte', ja: 'すべて', ko: '전체', ar: 'الكل', tr: 'Tümü', pl: 'Wszystkie', uk: 'Усі', nl: 'Alles', vi: 'Tất cả' }),
  'requests.statusPending': all({ en: 'Pending', ru: 'Ожидает', zh: '待处理', es: 'Pendiente', fr: 'En attente', de: 'Ausstehend', pt: 'Pendente', it: 'In attesa', ja: '保留中', ko: '대기 중', ar: 'قيد الانتظار', tr: 'Bekliyor', pl: 'Oczekuje', uk: 'Очікує', nl: 'In behandeling', vi: 'Đang chờ' }),
  'requests.statusApproved': all({ en: 'Approved', ru: 'Одобрен', zh: '已批准', es: 'Aprobada', fr: 'Approuvée', de: 'Genehmigt', pt: 'Aprovada', it: 'Approvata', ja: '承認済み', ko: '승인됨', ar: 'مقبول', tr: 'Onaylandı', pl: 'Zatwierdzone', uk: 'Схвалено', nl: 'Goedgekeurd', vi: 'Đã duyệt' }),
  'requests.statusRejected': all({ en: 'Rejected', ru: 'Отклонён', zh: '已拒绝', es: 'Rechazada', fr: 'Rejetée', de: 'Abgelehnt', pt: 'Rejeitada', it: 'Rifiutata', ja: '拒否済み', ko: '거부됨', ar: 'مرفوض', tr: 'Reddedildi', pl: 'Odrzucone', uk: 'Відхилено', nl: 'Afgewezen', vi: 'Đã từ chối' }),
  'requests.from': all({ en: 'from', ru: 'от', zh: '来自', es: 'de', fr: 'de', de: 'von', pt: 'de', it: 'da', ja: '作成者', ko: '작성자', ar: 'من', tr: 'kimden', pl: 'od', uk: 'від', nl: 'van', vi: 'từ' }),
  'requests.changes': all({ en: 'changes', ru: 'изменений', zh: '项更改', es: 'cambios', fr: 'modifications', de: 'Änderungen', pt: 'alterações', it: 'modifiche', ja: '変更', ko: '변경', ar: 'تغييرات', tr: 'değişiklik', pl: 'zmian', uk: 'змін', nl: 'wijzigingen', vi: 'thay đổi' }),
  'requests.approve': all({ en: 'Approve', ru: 'Одобрить', zh: '批准', es: 'Aprobar', fr: 'Approuver', de: 'Genehmigen', pt: 'Aprovar', it: 'Approva', ja: '承認', ko: '승인', ar: 'قبول', tr: 'Onayla', pl: 'Zatwierdź', uk: 'Схвалити', nl: 'Goedkeuren', vi: 'Duyệt' }),
  'requests.reject': all({ en: 'Reject', ru: 'Отклонить', zh: '拒绝', es: 'Rechazar', fr: 'Rejeter', de: 'Ablehnen', pt: 'Rejeitar', it: 'Rifiuta', ja: '拒否', ko: '거부', ar: 'رفض', tr: 'Reddet', pl: 'Odrzuć', uk: 'Відхилити', nl: 'Afwijzen', vi: 'Từ chối' }),
  'requests.noRequests': all({ en: 'No requests', ru: 'Запросов нет', zh: '没有请求', es: 'No hay solicitudes', fr: 'Aucune demande', de: 'Keine Anfragen', pt: 'Nenhuma solicitação', it: 'Nessuna richiesta', ja: 'リクエストなし', ko: '요청 없음', ar: 'لا توجد طلبات', tr: 'İstek yok', pl: 'Brak zgłoszeń', uk: 'Запитів немає', nl: 'Geen verzoeken', vi: 'Không có yêu cầu' }),
  'requests.noRequestsHint': all({ en: 'Translation change requests will appear here', ru: 'Запросы на изменение переводов появятся здесь', zh: '翻译更改请求将显示在这里', es: 'Las solicitudes de cambio de traducción aparecerán aquí', fr: 'Les demandes de modification de traduction apparaîtront ici', de: 'Änderungsanfragen für Übersetzungen erscheinen hier', pt: 'Solicitações de alteração de tradução aparecerão aqui', it: 'Le richieste di modifica traduzione appariranno qui', ja: '翻訳変更リクエストがここに表示されます', ko: '번역 변경 요청이 여기에 표시됩니다', ar: 'ستظهر طلبات تغيير الترجمة هنا', tr: 'Çeviri değişiklik istekleri burada görünecek', pl: 'Tutaj pojawią się zgłoszenia zmian tłumaczeń', uk: 'Запити на зміну перекладів з’являться тут', nl: 'Wijzigingsverzoeken voor vertalingen verschijnen hier', vi: 'Yêu cầu thay đổi bản dịch sẽ xuất hiện ở đây' }),
  'requests.tryChangeFilters': all({ en: 'Try changing the filters', ru: 'Попробуйте изменить фильтры', zh: '尝试更改筛选器', es: 'Prueba a cambiar los filtros', fr: 'Essayez de changer les filtres', de: 'Versuchen Sie, die Filter zu ändern', pt: 'Tente alterar os filtros', it: 'Prova a cambiare i filtri', ja: 'フィルターを変更してみてください', ko: '필터를 변경해 보세요', ar: 'جرّب تغيير الفلاتر', tr: 'Filtreleri değiştirmeyi deneyin', pl: 'Spróbuj zmienić filtry', uk: 'Спробуйте змінити фільтри', nl: 'Probeer de filters te wijzigen', vi: 'Thử thay đổi bộ lọc' }),
  'requests.was': all({ en: 'WAS:', ru: 'БЫЛО:', zh: '原来：', es: 'ANTES:', fr: 'AVANT :', de: 'WAR:', pt: 'ERA:', it: 'ERA:', ja: '変更前:', ko: '이전:', ar: 'كان:', tr: 'ÖNCE:', pl: 'BYŁO:', uk: 'БУЛО:', nl: 'WAS:', vi: 'TRƯỚC:' }),
  'requests.became': all({ en: 'NOW:', ru: 'СТАЛО:', zh: '现在：', es: 'AHORA:', fr: 'MAINTENANT :', de: 'JETZT:', pt: 'AGORA:', it: 'ORA:', ja: '変更後:', ko: '현재:', ar: 'الآن:', tr: 'ŞİMDİ:', pl: 'JEST:', uk: 'СТАЛО:', nl: 'NU:', vi: 'SAU:' }),
  'requests.adminEditHint': all({ en: 'Administrator can correct translations before approval. The original string remains the key.', ru: 'Администратор может поправить переводы перед принятием. Оригинальная строка остается ключом.', zh: '管理员可以在批准前修正翻译。原始字符串仍作为键。', es: 'El administrador puede corregir traducciones antes de aprobar. La cadena original sigue siendo la clave.', fr: 'L’administrateur peut corriger les traductions avant approbation. La chaîne originale reste la clé.', de: 'Der Administrator kann Übersetzungen vor der Genehmigung korrigieren. Der Originaltext bleibt der Schlüssel.', pt: 'O administrador pode corrigir traduções antes da aprovação. A string original continua sendo a chave.', it: 'L’amministratore può correggere le traduzioni prima dell’approvazione. La stringa originale resta la chiave.', ja: '管理者は承認前に翻訳を修正できます。元の文字列がキーのままです。', ko: '관리자는 승인 전에 번역을 수정할 수 있습니다. 원문 문자열은 키로 유지됩니다.', ar: 'يمكن للمدير تصحيح الترجمات قبل الموافقة. تبقى السلسلة الأصلية هي المفتاح.', tr: 'Yönetici onaydan önce çevirileri düzeltebilir. Orijinal dize anahtar olarak kalır.', pl: 'Administrator może poprawić tłumaczenia przed zatwierdzeniem. Oryginalny ciąg pozostaje kluczem.', uk: 'Адміністратор може виправити переклади перед схваленням. Оригінальний рядок лишається ключем.', nl: 'De beheerder kan vertalingen corrigeren vóór goedkeuring. De originele string blijft de sleutel.', vi: 'Quản trị viên có thể sửa bản dịch trước khi duyệt. Chuỗi gốc vẫn là khóa.' }),
  'requests.adminCorrection': all({ en: 'Admin correction', ru: 'Правка администратора', zh: '管理员修正', es: 'Corrección del administrador', fr: 'Correction administrateur', de: 'Admin-Korrektur', pt: 'Correção do administrador', it: 'Correzione admin', ja: '管理者修正', ko: '관리자 수정', ar: 'تصحيح المدير', tr: 'Yönetici düzeltmesi', pl: 'Poprawka administratora', uk: 'Правка адміністратора', nl: 'Beheerderscorrectie', vi: 'Sửa bởi quản trị viên' }),
  'requests.resetCorrection': all({ en: 'Reset correction', ru: 'Сбросить правку', zh: '重置修正', es: 'Restablecer corrección', fr: 'Réinitialiser la correction', de: 'Korrektur zurücksetzen', pt: 'Redefinir correção', it: 'Ripristina correzione', ja: '修正をリセット', ko: '수정 초기화', ar: 'إعادة تعيين التصحيح', tr: 'Düzeltmeyi sıfırla', pl: 'Resetuj poprawkę', uk: 'Скинути правку', nl: 'Correctie resetten', vi: 'Đặt lại sửa đổi' }),
  'requests.approveWithCorrections': all({ en: 'Approve with corrections', ru: 'Принять с правками', zh: '带修正批准', es: 'Aprobar con correcciones', fr: 'Approuver avec corrections', de: 'Mit Korrekturen genehmigen', pt: 'Aprovar com correções', it: 'Approva con correzioni', ja: '修正して承認', ko: '수정 후 승인', ar: 'الموافقة مع التصحيحات', tr: 'Düzeltmelerle onayla', pl: 'Zatwierdź z poprawkami', uk: 'Прийняти з правками', nl: 'Goedkeuren met correcties', vi: 'Duyệt kèm sửa đổi' }),

  // Settings
  'settings.title': all({ en: 'Settings', ru: 'Настройки', zh: '设置', es: 'Ajustes', fr: 'Paramètres', de: 'Einstellungen', pt: 'Configurações', it: 'Impostazioni', ja: '設定', ko: '설정', ar: 'الإعدادات', tr: 'Ayarlar', pl: 'Ustawienia', uk: 'Налаштування', nl: 'Instellingen', vi: 'Cài đặt' }),
  'settings.subtitle': all({ en: 'Translation editor configuration', ru: 'Конфигурация редактора переводов', zh: '翻译编辑器配置', es: 'Configuración del editor de traducciones', fr: 'Configuration de l’éditeur de traductions', de: 'Konfiguration des Übersetzungseditors', pt: 'Configuração do editor de traduções', it: 'Configurazione editor traduzioni', ja: '翻訳エディター設定', ko: '번역 편집기 구성', ar: 'إعداد محرر الترجمات', tr: 'Çeviri düzenleyici yapılandırması', pl: 'Konfiguracja edytora tłumaczeń', uk: 'Конфігурація редактора перекладів', nl: 'Configuratie vertaaleditor', vi: 'Cấu hình trình chỉnh sửa bản dịch' }),
  'settings.limitedAccess': all({ en: 'Limited access', ru: 'Ограниченный доступ', zh: '受限访问', es: 'Acceso limitado', fr: 'Accès limité', de: 'Eingeschränkter Zugriff', pt: 'Acesso limitado', it: 'Accesso limitato', ja: '制限付きアクセス', ko: '제한된 접근', ar: 'وصول محدود', tr: 'Sınırlı erişim', pl: 'Ograniczony dostęp', uk: 'Обмежений доступ', nl: 'Beperkte toegang', vi: 'Quyền truy cập hạn chế' }),
  'settings.limitedAccessDesc': all({ en: 'Settings are read-only. Log in as administrator to modify settings.', ru: 'Настройки доступны только для просмотра. Войдите как администратор, чтобы изменять настройки.', zh: '设置为只读。请以管理员身份登录以修改设置。', es: 'Los ajustes son de solo lectura. Inicia sesión como administrador para modificarlos.', fr: 'Les paramètres sont en lecture seule. Connectez-vous comme administrateur pour les modifier.', de: 'Einstellungen sind schreibgeschützt. Melden Sie sich als Administrator an, um sie zu ändern.', pt: 'As configurações são somente leitura. Entre como administrador para modificá-las.', it: 'Le impostazioni sono in sola lettura. Accedi come amministratore per modificarle.', ja: '設定は読み取り専用です。変更するには管理者としてログインしてください。', ko: '설정은 읽기 전용입니다. 수정하려면 관리자로 로그인하세요.', ar: 'الإعدادات للقراءة فقط. سجّل الدخول كمدير لتعديلها.', tr: 'Ayarlar salt okunur. Değiştirmek için yönetici olarak giriş yapın.', pl: 'Ustawienia są tylko do odczytu. Zaloguj się jako administrator, aby je zmienić.', uk: 'Налаштування доступні лише для перегляду. Увійдіть як адміністратор, щоб змінювати їх.', nl: 'Instellingen zijn alleen-lezen. Log in als beheerder om ze te wijzigen.', vi: 'Cài đặt chỉ đọc. Đăng nhập quản trị viên để chỉnh sửa.' }),
  'settings.pathTitle': all({ en: 'Translation files path', ru: 'Путь к файлам перевода', zh: '翻译文件路径', es: 'Ruta de archivos de traducción', fr: 'Chemin des fichiers de traduction', de: 'Pfad der Übersetzungsdateien', pt: 'Caminho dos arquivos de tradução', it: 'Percorso file traduzione', ja: '翻訳ファイルのパス', ko: '번역 파일 경로', ar: 'مسار ملفات الترجمة', tr: 'Çeviri dosyaları yolu', pl: 'Ścieżka plików tłumaczeń', uk: 'Шлях до файлів перекладу', nl: 'Pad naar vertaalbestanden', vi: 'Đường dẫn tệp dịch' }),
  'settings.pathLabel': all({ en: 'Root path (from root)', ru: 'Корневой путь (от root)', zh: '根路径（从 root）', es: 'Ruta raíz (desde root)', fr: 'Chemin racine (depuis root)', de: 'Stammpfad (ab root)', pt: 'Caminho raiz (a partir de root)', it: 'Percorso root (da root)', ja: 'ルートパス（root から）', ko: '루트 경로(root 기준)', ar: 'المسار الجذري (من root)', tr: 'Kök yol (root üzerinden)', pl: 'Ścieżka główna (od root)', uk: 'Кореневий шлях (від root)', nl: 'Rootpad (vanaf root)', vi: 'Đường dẫn gốc (từ root)' }),
  'settings.pathHint': all({ en: 'Expected structure:', ru: 'Ожидаемая структура:', zh: '预期结构：', es: 'Estructura esperada:', fr: 'Structure attendue :', de: 'Erwartete Struktur:', pt: 'Estrutura esperada:', it: 'Struttura prevista:', ja: '期待される構造:', ko: '예상 구조:', ar: 'البنية المتوقعة:', tr: 'Beklenen yapı:', pl: 'Oczekiwana struktura:', uk: 'Очікувана структура:', nl: 'Verwachte structuur:', vi: 'Cấu trúc mong đợi:' }),
  'settings.pathIndex': all({ en: 'language index', ru: 'языковой индекс', zh: '语言索引', es: 'índice de idiomas', fr: 'index des langues', de: 'Sprachindex', pt: 'índice de idiomas', it: 'indice lingue', ja: '言語インデックス', ko: '언어 인덱스', ar: 'فهرس اللغات', tr: 'dil dizini', pl: 'indeks języków', uk: 'мовний індекс', nl: 'taalindex', vi: 'chỉ mục ngôn ngữ' }),
  'settings.pathRu': all({ en: 'Russian translation', ru: 'русский перевод', zh: '俄语翻译', es: 'traducción rusa', fr: 'traduction russe', de: 'russische Übersetzung', pt: 'tradução russa', it: 'traduzione russa', ja: 'ロシア語翻訳', ko: '러시아어 번역', ar: 'الترجمة الروسية', tr: 'Rusça çeviri', pl: 'tłumaczenie rosyjskie', uk: 'російський переклад', nl: 'Russische vertaling', vi: 'bản dịch tiếng Nga' }),
  'settings.pathCn': all({ en: 'Chinese translation', ru: 'китайский перевод', zh: '中文翻译', es: 'traducción china', fr: 'traduction chinoise', de: 'chinesische Übersetzung', pt: 'tradução chinesa', it: 'traduzione cinese', ja: '中国語翻訳', ko: '중국어 번역', ar: 'الترجمة الصينية', tr: 'Çince çeviri', pl: 'tłumaczenie chińskie', uk: 'китайський переклад', nl: 'Chinese vertaling', vi: 'bản dịch tiếng Trung' }),
  'settings.adminTitle': all({ en: 'Administrator credentials', ru: 'Учётные данные администратора', zh: '管理员凭据', es: 'Credenciales de administrador', fr: 'Identifiants administrateur', de: 'Administrator-Zugangsdaten', pt: 'Credenciais do administrador', it: 'Credenziali amministratore', ja: '管理者認証情報', ko: '관리자 자격 증명', ar: 'بيانات اعتماد المدير', tr: 'Yönetici kimlik bilgileri', pl: 'Dane administratora', uk: 'Облікові дані адміністратора', nl: 'Beheerdersgegevens', vi: 'Thông tin quản trị viên' }),
  'settings.adminLogin': all({ en: 'Login', ru: 'Логин', zh: '登录名', es: 'Usuario', fr: 'Identifiant', de: 'Login', pt: 'Login', it: 'Login', ja: 'ログイン', ko: '로그인', ar: 'تسجيل الدخول', tr: 'Giriş', pl: 'Login', uk: 'Логін', nl: 'Login', vi: 'Đăng nhập' }),
  'settings.adminPassword': all({ en: 'Password', ru: 'Пароль', zh: '密码', es: 'Contraseña', fr: 'Mot de passe', de: 'Passwort', pt: 'Senha', it: 'Password', ja: 'パスワード', ko: '비밀번호', ar: 'كلمة المرور', tr: 'Parola', pl: 'Hasło', uk: 'Пароль', nl: 'Wachtwoord', vi: 'Mật khẩu' }),
  'settings.adminHint': all({ en: 'The only system administrator for managing change requests', ru: 'Единственный администратор системы для управления запросами на изменение', zh: '用于管理更改请求的唯一系统管理员', es: 'El único administrador del sistema para gestionar solicitudes de cambio', fr: 'Le seul administrateur système pour gérer les demandes', de: 'Der einzige Systemadministrator zur Verwaltung von Änderungsanfragen', pt: 'O único administrador do sistema para gerenciar solicitações', it: 'L’unico amministratore di sistema per gestire le richieste', ja: '変更リクエストを管理する唯一のシステム管理者', ko: '변경 요청을 관리하는 유일한 시스템 관리자', ar: 'مدير النظام الوحيد لإدارة طلبات التغيير', tr: 'Değişiklik isteklerini yöneten tek sistem yöneticisi', pl: 'Jedyny administrator systemu do zarządzania zgłoszeniami', uk: 'Єдиний адміністратор системи для керування запитами', nl: 'De enige systeembeheerder voor wijzigingsverzoeken', vi: 'Quản trị viên hệ thống duy nhất để quản lý yêu cầu thay đổi' }),
  'settings.resetData': all({ en: 'Reset data', ru: 'Сбросить данные', zh: '重置数据', es: 'Restablecer datos', fr: 'Réinitialiser les données', de: 'Daten zurücksetzen', pt: 'Redefinir dados', it: 'Reimposta dati', ja: 'データをリセット', ko: '데이터 초기화', ar: 'إعادة تعيين البيانات', tr: 'Verileri sıfırla', pl: 'Resetuj dane', uk: 'Скинути дані', nl: 'Gegevens resetten', vi: 'Đặt lại dữ liệu' }),
  'settings.save': all({ en: 'Save settings', ru: 'Сохранить настройки', zh: '保存设置', es: 'Guardar ajustes', fr: 'Enregistrer les paramètres', de: 'Einstellungen speichern', pt: 'Salvar configurações', it: 'Salva impostazioni', ja: '設定を保存', ko: '설정 저장', ar: 'حفظ الإعدادات', tr: 'Ayarları kaydet', pl: 'Zapisz ustawienia', uk: 'Зберегти налаштування', nl: 'Instellingen opslaan', vi: 'Lưu cài đặt' }),
  'settings.saved': all({ en: 'Settings saved', ru: 'Настройки сохранены', zh: '设置已保存', es: 'Ajustes guardados', fr: 'Paramètres enregistrés', de: 'Einstellungen gespeichert', pt: 'Configurações salvas', it: 'Impostazioni salvate', ja: '設定を保存しました', ko: '설정이 저장됨', ar: 'تم حفظ الإعدادات', tr: 'Ayarlar kaydedildi', pl: 'Ustawienia zapisane', uk: 'Налаштування збережено', nl: 'Instellingen opgeslagen', vi: 'Đã lưu cài đặt' }),
  'settings.resetTitle': all({ en: 'Reset data?', ru: 'Сбросить данные?', zh: '重置数据？', es: '¿Restablecer datos?', fr: 'Réinitialiser les données ?', de: 'Daten zurücksetzen?', pt: 'Redefinir dados?', it: 'Reimpostare i dati?', ja: 'データをリセットしますか？', ko: '데이터를 초기화할까요?', ar: 'إعادة تعيين البيانات؟', tr: 'Veriler sıfırlansın mı?', pl: 'Zresetować dane?', uk: 'Скинути дані?', nl: 'Gegevens resetten?', vi: 'Đặt lại dữ liệu?' }),
  'settings.resetCannotUndo': all({ en: 'This action cannot be undone', ru: 'Это действие нельзя отменить', zh: '此操作无法撤销', es: 'Esta acción no se puede deshacer', fr: 'Cette action est irréversible', de: 'Diese Aktion kann nicht rückgängig gemacht werden', pt: 'Esta ação não pode ser desfeita', it: 'Questa azione non può essere annullata', ja: 'この操作は元に戻せません', ko: '이 작업은 되돌릴 수 없습니다', ar: 'لا يمكن التراجع عن هذا الإجراء', tr: 'Bu işlem geri alınamaz', pl: 'Tej akcji nie można cofnąć', uk: 'Цю дію не можна скасувати', nl: 'Deze actie kan niet ongedaan worden gemaakt', vi: 'Không thể hoàn tác hành động này' }),
  'settings.resetDesc': all({ en: 'All translations, change requests, and settings will be reset to default values.', ru: 'Все переводы, запросы на изменение и настройки будут сброшены до значений по умолчанию.', zh: '所有翻译、更改请求和设置都将重置为默认值。', es: 'Todas las traducciones, solicitudes de cambio y ajustes se restablecerán.', fr: 'Toutes les traductions, demandes et paramètres seront réinitialisés.', de: 'Alle Übersetzungen, Änderungsanfragen und Einstellungen werden zurückgesetzt.', pt: 'Todas as traduções, solicitações e configurações serão redefinidas.', it: 'Tutte le traduzioni, richieste e impostazioni saranno ripristinate.', ja: 'すべての翻訳、変更リクエスト、設定が既定値に戻ります。', ko: '모든 번역, 변경 요청, 설정이 기본값으로 초기화됩니다.', ar: 'سيتم إعادة تعيين كل الترجمات والطلبات والإعدادات إلى القيم الافتراضية.', tr: 'Tüm çeviriler, istekler ve ayarlar varsayılan değerlere sıfırlanacak.', pl: 'Wszystkie tłumaczenia, zgłoszenia i ustawienia zostaną przywrócone.', uk: 'Усі переклади, запити та налаштування буде скинуто.', nl: 'Alle vertalingen, verzoeken en instellingen worden gereset.', vi: 'Tất cả bản dịch, yêu cầu và cài đặt sẽ được đặt lại.' }),
  'settings.resetConfirm': all({ en: 'Reset', ru: 'Сбросить', zh: '重置', es: 'Restablecer', fr: 'Réinitialiser', de: 'Zurücksetzen', pt: 'Redefinir', it: 'Reimposta', ja: 'リセット', ko: '초기화', ar: 'إعادة تعيين', tr: 'Sıfırla', pl: 'Resetuj', uk: 'Скинути', nl: 'Resetten', vi: 'Đặt lại' }),
  'settings.cancel': all({ en: 'Cancel', ru: 'Отмена', zh: '取消', es: 'Cancelar', fr: 'Annuler', de: 'Abbrechen', pt: 'Cancelar', it: 'Annulla', ja: 'キャンセル', ko: '취소', ar: 'إلغاء', tr: 'İptal', pl: 'Anuluj', uk: 'Скасувати', nl: 'Annuleren', vi: 'Hủy' }),


  'settings.loadTitle': all({ en: 'Load translation files', ru: 'Загрузка файлов перевода' }),
  'settings.loadServer': all({ en: 'Load from Server', ru: 'Загрузить с сервера' }),
  'settings.loadServerDesc': all({ en: 'Read all localization files through the backend API', ru: 'Прочитать все файлы локализации через backend API' }),
  'settings.rewardsTitle': all({ en: 'Translation rewards', ru: 'Награды перевода' }),
  'settings.rewardsEnable': all({ en: 'Enable event', ru: 'Включить ивент' }),
  'settings.rewardsEnableDesc': all({ en: 'Show the event progress and rewards to all users above the leaderboard.', ru: 'Показывать всем пользователям прогресс и награды над топом.' }),
  'settings.rewardsEndDate': all({ en: 'End date', ru: 'Дата завершения' }),
  'settings.rewardsText': all({ en: 'Rewards', ru: 'Награды' }),
  'settings.rewardsPlaceholder': all({ en: 'Describe rewards, rules, places, or conditions...', ru: 'Опишите награды, правила, места или условия...' }),
  'settings.saveRewards': all({ en: 'Save rewards', ru: 'Сохранить награды' }),
  'settings.saving': all({ en: 'Saving...', ru: 'Сохранение...' }),
  'settings.topTitle': all({ en: 'Leaderboard', ru: 'Топ пользователей' }),
  'settings.resetTop': all({ en: 'Reset current top', ru: 'Сбросить текущий топ' }),
  'settings.resetTopHint': all({ en: 'Resets the visible leaderboard from this moment. Approved requests before the reset are kept in history, but no longer count in the current top.', ru: 'Сбрасывает видимый топ с текущего момента. Одобренные запросы до сброса остаются в истории, но больше не учитываются в текущем топе.' }),
  'settings.resetTopDesc': all({ en: 'The current leaderboard will be cleared and future accepted translations will start counting from now.', ru: 'Текущий топ будет очищен, а будущие принятые переводы начнут учитываться с этого момента.' }),
  'event.title': all({ en: 'Translation event', ru: 'Ивент переводов' }),
  'event.subtitle': all({ en: 'Progress and rewards', ru: 'Прогресс и награды' }),
  'event.rewards': all({ en: 'Rewards', ru: 'Награды' }),
  'event.daysLeft': all({ en: 'days left', ru: 'дн. осталось' }),
  'event.finished': all({ en: 'Finished', ru: 'Завершено' }),
  'event.noEndDate': all({ en: 'No end date', ru: 'Дата не задана' }),
  'sidebar.current': all({ en: 'Selected file', ru: 'Выбранный файл' }),
  'sidebar.searchLanguages': all({ en: 'Search language...', ru: 'Поиск языка...' }),
  'sidebar.noLanguages': all({ en: 'No languages found', ru: 'Языки не найдены' }),
  'sidebar.languageHotkeys': all({ en: 'Alt + ↑ / ↓ switches languages', ru: 'Alt + ↑ / ↓ переключает языки' }),
  'editor.previousLanguage': all({ en: 'Previous language', ru: 'Предыдущий язык' }),
  'editor.nextLanguage': all({ en: 'Next language', ru: 'Следующий язык' }),
  'editor.jumpLanguage': all({ en: 'Select language file', ru: 'Выбрать файл языка' }),
} as const;

export type TranslationKey = keyof typeof translations;

let currentLanguage: UILanguage = 'en';

export function setUILanguage(lang: UILanguage) {
  currentLanguage = UI_LANGUAGE_OPTIONS.some(option => option.code === lang) ? lang : 'en';
}

export function getUILanguage(): UILanguage {
  return currentLanguage;
}

export function t(key: TranslationKey): string {
  const entry = translations[key];
  if (!entry) return key;
  return entry[currentLanguage] || entry.en || key;
}
