#ifndef ENGINE_SHARED_PROTOCOL_EX_H
#define ENGINE_SHARED_PROTOCOL_EX_H

#include <engine/shared/uuid_manager.h>

class CMsgPacker;
class CUnpacker;

enum
{
	NETMSG_EX_INVALID = UUID_INVALID,
	NETMSG_EX_UNKNOWN = UUID_UNKNOWN,

	OFFSET_NETMSG_UUID = OFFSET_UUID,

	__NETMSG_UUID_HELPER = OFFSET_NETMSG_UUID - 1,
#define UUID(id, name) id,
#include "protocol_ex_msgs.h"
#undef UUID
	OFFSET_TEEHISTORIAN_UUID,
	__TEEHISTORIAN_UUID_HELPER = OFFSET_TEEHISTORIAN_UUID - 1,
	TEEHISTORIAN_TEST,
	TEEHISTORIAN_DDNETVER_OLD,
	TEEHISTORIAN_DDNETVER,
	TEEHISTORIAN_AUTH_INIT,
	TEEHISTORIAN_AUTH_LOGIN,
	TEEHISTORIAN_AUTH_LOGOUT,
	TEEHISTORIAN_JOINVER6,
	TEEHISTORIAN_JOINVER7,
	TEEHISTORIAN_PLAYER_SWITCH,
	TEEHISTORIAN_SAVE_SUCCESS,
	TEEHISTORIAN_SAVE_FAILURE,
	TEEHISTORIAN_LOAD_SUCCESS,
	TEEHISTORIAN_LOAD_FAILURE,
	TEEHISTORIAN_PLAYER_TEAM,
	TEEHISTORIAN_TEAM_PRACTICE,
	TEEHISTORIAN_PLAYER_READY,

	// from ddnet 65564
	OFFSET_GAME_UUID, 

	UNPACKMESSAGE_ERROR = 0,
	UNPACKMESSAGE_OK,
	UNPACKMESSAGE_ANSWER,

	SERVERCAP_CURVERSION = 5,
	SERVERCAPFLAG_DDNET = 1 << 0,
	SERVERCAPFLAG_CHATTIMEOUTCODE = 1 << 1,
	SERVERCAPFLAG_ANYPLAYERFLAG = 1 << 2,
	SERVERCAPFLAG_PINGEX = 1 << 3,
	SERVERCAPFLAG_ALLOWDUMMY = 1 << 4,
	SERVERCAPFLAG_SYNCWEAPONINPUT = 1 << 5,
};

void RegisterUuids(CUuidManager *pManager);
bool NetworkExDefaultHandler(int *pID, CUuid *pUuid, CUnpacker *pUnpacker, CMsgPacker *pPacker, int Type);

int UnpackMessageID(int *pID, bool *pSys, CUuid *pUuid, CUnpacker *pUnpacker, CMsgPacker *pPacker);

#endif // ENGINE_SHARED_PROTOCOL_EX_H
