name: Server Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - name: "Ubuntu x86_64"
          os: ubuntu-latest
          cmake-args: -G "Unix Makefiles"
          package-file: mmoteeworlds-linux_x86_64.tar.xz
          package-full-file: mmoteeworlds-linux_x86_64-full.tar.xz
          env:
            CFLAGS: -Wdeclaration-after-statement -Wduplicated-branches -Wno-unused-function -Wno-unused-variable -Werror
            CXXFLAGS: -Wduplicated-branches -Wno-unused-function -Wno-unused-variable -Werror
            
        - name: "Windows"
          os: windows-latest
          cmake-args: -A x64
          package-file: mmoteeworlds-win64.zip
          package-full-file: mmoteeworlds-win64-full.zip
          env:
            CFLAGS: /WX
            CXXFLAGS: /WX
            LDFLAGS: /WX

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install pkg-config cmake libicu-dev libssl-dev libcurl4-openssl-dev -y
        sudo apt-get install libboost-dev libmariadb-dev libmysqlcppconn-dev -y
    - name: Build
      env: ${{ matrix.env }}
      run: |
        mkdir release
        cd release
        ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release -Werror=dev -DDOWNLOAD_GTEST=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=. ..
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }} --target package_default --parallel $(nproc)
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }} --target mmoteeworlds_srv --parallel $(nproc)
    - name: Package(Linux)
      if: contains(matrix.os, 'ubuntu')
      run: |
        mkdir release/artifacts
        cd release
        mv mmoteeworlds_srv ..
        mv ${{ matrix.package-file }} ..
        cd ..
        tar -cf ${{ matrix.package-full-file }} ${{ matrix.package-file }}
        mv ${{ matrix.package-full-file }} release/artifacts
    - name: Package(Windows)
      if: contains(matrix.os, 'windows')
      run: |
        mkdir release/artifacts
        cd release
        mv mmoteeworlds_srv.exe ..
        mv ${{ matrix.package-file }} ..
        cd ..
        7z a ${{ matrix.package-full-file }} ${{ matrix.package-file }}
        mv ${{ matrix.package-full-file }} release/artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: release/artifacts/${{ matrix.package-full-file }}
